pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet pack --configuration $(buildConfiguration) -o ./

- script: dotnet tool install gpr --tool-path ./bin

- pwsh: |
    $nupkg = (Get-ChildItem -Filter *.nupkg -Recurse).FullName[0]
    ./bin/gpr push $nupkg -k $(TOKEN) --owner MisinformedDNA
