trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet pack --configuration $(buildConfiguration) -o ./

- script: dotnet tool install gpr --tool-path ./bin

- pwsh: gci -Recurse

- script: ./bin/gpr push Swashbuckle.AspNetCore.AzureFunctions.1.1.1.nupkg -k $(TOKEN) --owner MisinformedDNA
