trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet pack --configuration $(buildConfiguration) -o ./

- script: dotnet tool install gpr --tool-path ./bin

- pwsh: gci -Recurse

- script: dotnet nuget add source https://nuget.pkg.github.com/misinformeddna/index.json -n github -u MisinformedDNA -p NOTSET --store-password-in-clear-text

- script: ./bin/gpr push ./*.nupkg -k $(TOKEN)